platform :ios, '15.0' 

source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'


# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # update MLKitVision version to match mobile_scanner requirements FOR APP STORE UPLOAD
  pod 'GoogleMLKit/BarcodeScanning', '~> 4.0.0'
  pod 'PromisesObjC', '~> 2.3.1'  # add explicit dependency for FBLPromises

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  # for xcode 14
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEAD_CODE_STRIPPING'] = 'YES'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['SWIFT_EMIT_LOC_STRINGS'] = 'YES'
        config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
        config.build_settings['SWIFT_PRECOMPILE_BRIDGING_HEADER'] = 'YES'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['FRAMEWORK_SEARCH_PATHS'] = [
          '$(inherited)',
          '${PODS_ROOT}/**',
          '${PODS_XCFRAMEWORKS_BUILD_DIR}/**'
        ]
        
        # Ensure Runner target has proper module settings
        if target.name == 'Runner'
          config.build_settings['DEFINES_MODULE'] = 'YES'
          config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
          config.build_settings['SWIFT_PRECOMPILE_BRIDGING_HEADER'] = 'YES'
          config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
          config.build_settings['PRODUCT_MODULE_NAME'] = target.name
        end
      end
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
