name: Build iPadOS (iOS)

on:
  workflow_dispatch:
    inputs:
      comments:
        description: "Comments"
        required: false
        default: "Nothing"
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build_info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Worker Comments: $BUILD_CMTS"
        env:
          BUILD_CMTS: ${{ inputs.comments }}

  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          channel: "stable"
          cache: true
      
      - name: Check Flutter Version
        run: flutter --version
      
      - name: Clean and Get Dependencies
        run: |
          flutter clean
          flutter pub get
        
      - name: Setup CocoaPods
        run: |
          cd ios
          pod install
          cd ..
        
      - name: Build iOS
        run: flutter build ios --release --no-codesign --no-tree-shake-icons --verbose
        
      - name: Build IPA
        run: flutter build ipa --release --no-codesign --no-tree-shake-icons --verbose
        
      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS_Build
          path: |
            build/ios/iphoneos
            build/ios/archive/Runner.xcarchive
          retention-days: 5
