name: Flutter Web
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    - run: flutter config --enable-web
    - run: flutter pub get
    # Build with different base-href depending on custom domain
    - name: Build Flutter Web
      run: |
        if [ -f "CNAME" ]; then
          flutter build web --base-href "/"
        else
          flutter build web --base-href "/ScoutingApp2025/"
        fi
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
    - run: flutter build web --release --no-tree-shake-icons
    - name: Copy fonts to build
      run: |
        mkdir -p build/web/fonts
        cp fonts/MaterialIcons-Regular.otf build/web/fonts/