name: Flutter Web
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter clean
    - name: Build Flutter Web
      run: |
        if [ -f "CNAME" ]; then
          flutter build web --base-href "/" --release \
            --dart-define=FLUTTER_WEB_CANVASKIT_URL=canvaskit/ \
            --web-renderer canvaskit
        else
          flutter build web --base-href "/ScoutingApp2025/" --release \
            --dart-define=FLUTTER_WEB_CANVASKIT_URL=canvaskit/ \
            --web-renderer canvaskit
        fi
    # Ensure fonts directory exists and copy fonts
    - name: Setup Web Fonts
      run: |
        mkdir -p build/web/fonts
        if [ -d "build/web/assets/fonts" ]; then
          cp -r build/web/assets/fonts/* build/web/fonts/
        fi
    - name: Create CNAME file
      run: echo "scoutingapp2025.wchiming.com" > build/web/CNAME
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        cname: scoutingapp2025.wchiming.com