name: Flutter Web
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter clean
    - name: Build Flutter Web
      run: |
        if [ -f "CNAME" ]; then
          flutter build web --base-href "/" --release
        else
          flutter build web --base-href "/ScoutingApp2025/" --release
        fi
    - name: Create CNAME file
      run: echo "scoutingapp2025.wchiming.com" > build/web/CNAME
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
        cname: scoutingapp2025.wchiming.com