name: Flutter Web
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'
    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web --base-href "/${{ github.event.repository.name }}/"
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
